from core import Constants


class CreateAd(Constants):
    __with_class_name__ = True

    region = ...
    city = ...
    institution_type = ...
    institution_name = ...
    institution_address = ...
    vacancies_amount = ...
    vacancy_title = ...
    work_experience = ...
    salary = ...
    schedule = ...
    working_hours = ...
    extra_info = ...
    contact_phone = ...
    photo = ...
    pin_option = ...
    post_date = ...
    duplicate_option = ...
    ad_preview = ...
